### ISSUE TITLE
Javascript Object-Oriented Course to be Completed

### ISSUE THREAD

**Issue by jordanmor** [jordanmor/Treehouse#2]
## TODO

*Steps left to complete the Treehouse Javascript Object-Oriented Track

- [ ] Build basic Quiz structure with HTML and CSS
- [ ] Come up with at least three questions and answers for the quiz
- [ ] Complete the Quiz using g object-oriented Javascript

🎉  😄
